system:
  mode: 0 # 0 for graph mode, 1 for pynative mode in MindSpore
  distribute: True
  amp_level: 'O2'
  seed: 42
  log_interval: 50
  val_while_train: True
  drop_overflow_update: False

common:
  character_dict_path: &character_dict_path ./mindocr/utils/dict/latex_symbol_dict.txt
  use_space_char: &use_space_char False
  blank_at_last: &blank_at_last True
  lower: &lower False
  batch_size: &batch_size 8
  max_text_len: &max_text_len 97
  word_num: &word_num 111
  ratio: &ratio 16

model:
  type: rec
  transform: null
  resume: False
  backbone:
    name: rec_densenet
    pretrained: False
  
  head:
    name: CANHead
    out_channels: *word_num
    ratio: *ratio
    attdecoder_args: 
      input_size: 256
      hidden_size: 256
      out_channels: 684
      attention_dim: 512
      word_num: *word_num
      counting_num: *word_num
      word_conv_kernel: 1
      dropout: 0.5

postprocess:
  name: CANLabelDecode
  character_dict_path: *character_dict_path
  use_space_char: *use_space_char
  blank_at_last: *blank_at_last
  lower: *lower

metric:
  name: CANMetric
  main_indicator: ExpRate 

loss:
  name: CANLoss
  ratio: *ratio
  out_channels: *word_num
  use_label_mask: True
  tag: True

scheduler:
  scheduler: cosine_decay
  lr: 1.0
  min_lr: 0.0
  warmup_epochs: 1
  warmup_factor: 0.0
  decay_epochs: 239
  num_epochs: 240

optimizer:
  opt: adadelta
  weight_decay: 0.0001

train:
  ema: True
  ema_decay: 0.9999
  clip_grad: True
  clip_norm: 100.0
  ckpt_save_dir: './tmp_can'
  dataset_sink_mode: False
  pred_cast_fp32: True
  dataset:
    type: DetDataset
    dataset_root: ./datasets/CROHME # Optional, if set, dataset_root will be used as a prefix for data_dir
    data_dir: training/images
    label_file: training/labels.txt
    # label_file: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: True
    filter_max_len: True
    max_text_len: *max_text_len
    transform_pipeline:
      - DecodeImage:
          channel_first: False
      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec.
          is_hwc: True
          mean: [0, 0, 0]
          std: [255, 255, 255]
      - CANResizeImg:
          image_shape: [128, 536]
      - GrayImageChannelFormat:
          inverse: True 
      - CANLabelEncode:
          max_text_len: *max_text_len
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          blank_at_last: *blank_at_last
          lower: *lower
      - CANGenCountingLabel:
          out_channels: *word_num
          tag: True

    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'image_mask', 'label', 'label_mask', 'counting_label']
    net_input_column_index: [0, 1, 2] # input indices for network forward func in output_columns
    label_column_index: [2, 3, 4] # input indices marked as label

  loader:
      shuffle: True # TODO: tbc
      batch_size: *batch_size
      drop_remainder: True
      max_rowsize: 16
      num_workers: 8

eval:
  ckpt_load_path: ./tmp_can/best.ckpt
  dataset_sink_mode: False
  pred_cast_fp32: True
  dataset:
    type: DetDataset
    dataset_root: ./datasets/CROHME # Optional, if set, dataset_root will be used as a prefix for data_dir
    data_dir: evaluation/images
    label_file: evaluation/labels.txt
    # label_file: # not required when using LMDBDataset
    sample_ratio: 1.0
    shuffle: False
    filter_max_len: True
    max_text_len: 205
    transform_pipeline:
      - DecodeImage:
          channel_first: False
      - NormalizeImage:  # different from paddle (paddle wrongly normalize BGR image with RGB mean/std from ImageNet for det, and simple rescale to [-1, 1] in rec.
          is_hwc: True
          mean: [0, 0, 0]
          std: [255, 255, 255]
      - CANResizeImg:
          image_shape: [128, 536]
      - GrayImageChannelFormat:
          inverse: True 
      - CANLabelEncode:
          max_text_len: 205
          character_dict_path: *character_dict_path
          use_space_char: *use_space_char
          blank_at_last: *blank_at_last
          lower: *lower
      - CANGenCountingLabel:
          out_channels: *word_num
          tag: True
  
    #  the order of the dataloader list, matching the network input and the input labels for the loss function, and optional data for debug/visaulize
    output_columns: ['image', 'image_mask', 'label', 'label_mask', 'counting_label']
    net_input_column_index: [0, 1, 2] # input indices for network forward func in output_columns
    label_column_index: [2, 3, 4] # input indices marked as label

  loader:
      shuffle: False # TODO: tbc
      batch_size: *batch_size
      drop_remainder: False
      max_rowsize: 16
      num_workers: 8